apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: dask-scheduler
    app: dask
  name: dask-scheduler
spec:
  replicas: 1
  selector:
    name: dask-scheduler
  template:
    metadata:
      labels:
        name: dask-scheduler
        app: dask
    spec:
      containers:
        - name: dask-scheduler
          image: mdurant/docker-distributed:renew
          args: ["dask-scheduler"]
          ports:
          - name: rpc
            containerPort: 8786
          - name: http
            containerPort: 9786
          - name: bokeh-internal
            containerPort: 8788
          - name: bokeh
            containerPort: 8787
          resources:
            requests: 
              cpu: 1
              memory: 1024Mi
          imagePullPolicy: IfNotPresent