apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: jupyter-notebook
    app: dask
  name: jupyter-notebook
spec:
  replicas: 1
  selector:
    name: jupyter-notebook
  template:
    metadata:
      labels:
        name: jupyter-notebook
    spec:
      containers:
        - name: jupyter-notebook
          image: mdurant/docker-distributed:renew
          args: ["jupyter", "notebook", "--config=/work/config/jupyter_notebook_config.py", "/work"]
          ports:
            - name: http
              containerPort: 8888
          resources:
            requests:
              cpu: 1
              memory: 4Gi
          imagePullPolicy: IfNotPresent
          securityContext:
            runAsUser: 1000
          workingDir: /work
