apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: jupyter-notebook
    app: dask
  name: jupyter-notebook
spec:
  replicas: 1
  selector:
    name: jupyter-notebook
  template:
    metadata:
      labels:
        name: jupyter-notebook
        app: dask
    spec:
      containers:
        - name: jupyter-notebook
          image: {{jupyter.image}}
          args: ["bash", "/work/config/start.sh"]
          ports:
            - name: http
              containerPort: 8888
            - name: lab-http
              containerPort: 8889
          resources:
            requests:
              cpu: {{jupyter.cpus}}
              memory: {{jupyter.memory}}
          imagePullPolicy: Always
          securityContext:
            runAsUser: 1000
          workingDir: /work
